shortest_path:
    path:     /api/path/{username1}/{username2}
    defaults: { _controller: AppBundle:API:shortestPath }
    methods:  [GET]

potentials:
    path:     /api/packages/{vendorName}/{packageName}/potentials
    defaults: { _controller: AppBundle:API:potentialContributors }
    methods:  [GET]

api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /api/doc
        permanent: true